{   
    "extends": "eslint:recommended",
    "env": { 
        "es6": true,
        "browser": true,
        "node": true,
        },
    "parserOptions": {
        "ecmaVersion": 6,
        "sourceType": "module",
        "ecmaFeatures": {
            "jsx": true
        }
    },
    "rules": {
        "semi": ["error", "always"],
        "quotes": ["error", "single"]
    },
    "overrides": [
        {
            "files": ["source/**/*.js"],
        }
    ]
        
}