{   
    "extends": "eslint:recommended",
    "env": { "es6": true },
    "rules": {
        "semi": ["error", "always"],
        "quotes": ["error", "double"]
    },
    "overrides": [
        {
            "files": ["source/**/*.js"],
        }
    ]
        
}